/* Automatically generated by po2tbl.sed from @PACKAGE NAME@.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Click Me", 2},
  {"The button was clicked.", 3},
  {"Hello, GTKmm World!", 4},
  {"Sample application for C++ programmers", 5},
};

int _msg_tbl_length = 5;
